spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sistemaAtividade?useSSL=false&createDatabaseIfNotExist=true
    username: root
    password: Joao4setto
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    properties:
      hibernate:
        show_sql: true
        hbm2ddl:
          auto: update